apiVersion: 1.0.0                              

previews:
  - name: insurance-frontend                                  
    container:
      image: us-east1-docker.pkg.dev/core-workshop/workshop-registry/pipeline-workshop/insurance-frontend:${{env.commit.sha}}
      ports:
      - value: 80                                  
    env:                                          
      FM_KEY: "61f462a5498b12caa9a6f84a"                     
