apiVersion: 1.0.0                              

previews:
  - name: insurance-frontend                                  
    container:
      image: us-east1-docker.pkg.dev/core-workshop/workshop-registry/insurance-frontend:bee-ci2
      ports:
      - value: 80                              
